version: "3"
services:
  nginx:
    image: nginx:1.14
    container_name: c_nginx
    ports:
      #需要暴露的端口映射
      - "8080:80"
      - "8081:81"
    volumes:
      - ./www:/home/wwwroot:rw
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:rw
      - ./nginx/conf.d:/etc/nginx/conf.d:rw
      - ./nginx/vhost:/etc/nginx/vhost:rw
      - ./nginx/base:/etc/nginx/base:rw
      - ./log/nginx:/home/wwwlogs:rw
    environment:
      TZ: "Asia/Shanghai"
    restart: always
    networks:
      - lnmp
  php:
    image: php:7.4-fpm
    container_name: php74
    volumes:
      - ./log/php:/home/wwwlogs:rw
      - ./www:/home/wwwroot:rw
      - ./php/74/php.ini:/usr/local/etc/php/php.ini:rw
    restart: always
    cap_add:
      - SYS_PTRACE
    depends_on:
      - nginx
    networks:
      - lnmp
networks:
  #创建一个自定义网络 lnmp
  lnmp: